2022-03-02 11:47:59,987 INFO    MainThread:3921 [internal.py:wandb_internal():89] W&B internal server running at pid: 3921, started at: 2022-03-02 11:47:59.987782
2022-03-02 11:47:59,988 INFO    WriterThread:3921 [datastore.py:open_for_write():77] open: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/run-17z6q4g1.wandb
2022-03-02 11:47:59,988 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: check_version
2022-03-02 11:47:59,989 DEBUG   SenderThread:3921 [sender.py:send():235] send: header
2022-03-02 11:47:59,989 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: check_version
2022-03-02 11:48:00,791 DEBUG   SenderThread:3921 [sender.py:send():235] send: run
2022-03-02 11:48:01,252 INFO    SenderThread:3921 [dir_watcher.py:__init__():169] watching files in: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files
2022-03-02 11:48:01,252 INFO    SenderThread:3921 [sender.py:_start_run_threads():809] run started: 17z6q4g1 with start time 1646218079
2022-03-02 11:48:01,253 DEBUG   SenderThread:3921 [sender.py:send():235] send: summary
2022-03-02 11:48:01,254 INFO    SenderThread:3921 [sender.py:_save_file():944] saving file wandb-summary.json with policy end
2022-03-02 11:48:01,257 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: run_start
2022-03-02 11:48:01,259 DEBUG   HandlerThread:3921 [meta.py:__init__():36] meta init
2022-03-02 11:48:01,260 DEBUG   HandlerThread:3921 [meta.py:__init__():50] meta init done
2022-03-02 11:48:01,260 DEBUG   HandlerThread:3921 [meta.py:probe():210] probe
2022-03-02 11:48:01,268 DEBUG   HandlerThread:3921 [git.py:repo():33] git repository is invalid
2022-03-02 11:48:01,269 DEBUG   HandlerThread:3921 [meta.py:_save_pip():54] save pip
2022-03-02 11:48:01,270 DEBUG   HandlerThread:3921 [meta.py:_save_pip():68] save pip done
2022-03-02 11:48:01,270 DEBUG   HandlerThread:3921 [meta.py:_save_conda():75] save conda
2022-03-02 11:48:02,258 INFO    Thread-8  :3921 [dir_watcher.py:_on_file_created():217] file/dir created: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/conda-environment.yaml
2022-03-02 11:48:02,258 INFO    Thread-8  :3921 [dir_watcher.py:_on_file_created():217] file/dir created: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/requirements.txt
2022-03-02 11:48:02,258 INFO    Thread-8  :3921 [dir_watcher.py:_on_file_created():217] file/dir created: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/wandb-summary.json
2022-03-02 11:48:04,796 DEBUG   HandlerThread:3921 [meta.py:_save_conda():85] save conda done
2022-03-02 11:48:04,796 DEBUG   HandlerThread:3921 [meta.py:probe():248] probe done
2022-03-02 11:48:04,799 DEBUG   SenderThread:3921 [sender.py:send():235] send: files
2022-03-02 11:48:04,799 INFO    SenderThread:3921 [sender.py:_save_file():944] saving file wandb-metadata.json with policy now
2022-03-02 11:48:04,802 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:48:04,802 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:48:05,121 DEBUG   SenderThread:3921 [sender.py:send():235] send: config
2022-03-02 11:48:05,271 INFO    Thread-8  :3921 [dir_watcher.py:_on_file_modified():230] file/dir modified: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/conda-environment.yaml
2022-03-02 11:48:05,271 INFO    Thread-8  :3921 [dir_watcher.py:_on_file_created():217] file/dir created: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/output.log
2022-03-02 11:48:05,271 INFO    Thread-8  :3921 [dir_watcher.py:_on_file_created():217] file/dir created: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/wandb-metadata.json
2022-03-02 11:48:05,857 INFO    Thread-11 :3921 [upload_job.py:push():137] Uploaded file /var/folders/wb/gdwc4q3s1x3cv4bftb9vssb00000gn/T/tmpcqm3gf_twandb/1smhw8lj-wandb-metadata.json
2022-03-02 11:48:07,282 INFO    Thread-8  :3921 [dir_watcher.py:_on_file_modified():230] file/dir modified: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/output.log
2022-03-02 11:48:11,311 INFO    Thread-8  :3921 [dir_watcher.py:_on_file_modified():230] file/dir modified: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/output.log
2022-03-02 11:48:20,847 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:48:21,085 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:48:30,599 DEBUG   SenderThread:3921 [sender.py:send():235] send: stats
2022-03-02 11:48:31,464 INFO    Thread-8  :3921 [dir_watcher.py:_on_file_modified():230] file/dir modified: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/config.yaml
2022-03-02 11:48:36,923 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:48:36,924 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:48:52,246 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:48:52,251 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:49:02,053 DEBUG   SenderThread:3921 [sender.py:send():235] send: stats
2022-03-02 11:49:07,678 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:49:07,680 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:49:23,726 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:49:23,747 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:49:33,312 DEBUG   SenderThread:3921 [sender.py:send():235] send: stats
2022-03-02 11:49:43,908 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:49:43,977 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:50:00,267 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:50:00,292 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:50:04,645 DEBUG   SenderThread:3921 [sender.py:send():235] send: stats
2022-03-02 11:50:15,714 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:50:15,726 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:50:31,182 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:50:31,185 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:50:36,140 DEBUG   SenderThread:3921 [sender.py:send():235] send: stats
2022-03-02 11:50:47,102 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:50:47,109 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:51:02,701 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:51:02,702 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:51:07,611 DEBUG   SenderThread:3921 [sender.py:send():235] send: stats
2022-03-02 11:51:18,439 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:51:18,439 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:51:33,897 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:51:33,922 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:51:39,088 DEBUG   SenderThread:3921 [sender.py:send():235] send: stats
2022-03-02 11:51:49,568 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:51:49,639 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:52:05,439 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:52:05,441 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:52:10,605 DEBUG   SenderThread:3921 [sender.py:send():235] send: stats
2022-03-02 11:52:21,471 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:52:21,483 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:52:36,896 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:52:36,913 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:52:42,090 DEBUG   SenderThread:3921 [sender.py:send():235] send: stats
2022-03-02 11:52:52,773 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:52:52,777 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:53:08,178 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:53:08,205 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:53:16,016 DEBUG   SenderThread:3921 [sender.py:send():235] send: stats
2022-03-02 11:53:25,812 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:53:25,832 DEBUG   SenderThread:3921 [sender.py:send_request():249] send_request: stop_status
2022-03-02 11:53:39,855 ERROR   SenderThread:3921 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x12008aca0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12008aca0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12008aca0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-03-02 11:53:44,705 INFO    Thread-8  :3921 [dir_watcher.py:_on_file_modified():230] file/dir modified: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/output.log
2022-03-02 11:53:45,822 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:54:06,254 DEBUG   HandlerThread:3921 [handler.py:handle_request():131] handle_request: stop_status
2022-03-02 11:54:10,756 WARNING MainThread:3921 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-03-02 11:54:11,763 WARNING MainThread:3921 [internal.py:is_dead():380] Internal process exiting, parent pid 3684 disappeared
2022-03-02 11:54:11,764 ERROR   MainThread:3921 [internal.py:wandb_internal():148] Internal process shutdown.
2022-03-02 11:54:12,282 INFO    WriterThread:3921 [datastore.py:close():281] close: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/run-17z6q4g1.wandb
2022-03-02 11:54:12,343 INFO    HandlerThread:3921 [handler.py:finish():739] shutting down handler
2022-03-02 11:55:28,588 WARNING FileStreamThread:3921 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: ('Connection aborted.', OSError(65, 'No route to host')). func: <bound method Session.post of <requests.sessions.Session object at 0x1200107c0>>, args: ("https://api.wandb.ai/files/wwy/Basic_UNet_['CTV1']/17z6q4g1/file_stream",), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-03-02 11:55:31,025 WARNING FileStreamThread:3921 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic_UNet_%5B'CTV1'%5D/17z6q4g1/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x120544e80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x1200107c0>>, args: ("https://api.wandb.ai/files/wwy/Basic_UNet_['CTV1']/17z6q4g1/file_stream",), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-03-02 11:55:35,068 WARNING FileStreamThread:3921 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic_UNet_%5B'CTV1'%5D/17z6q4g1/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x120544520>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x1200107c0>>, args: ("https://api.wandb.ai/files/wwy/Basic_UNet_['CTV1']/17z6q4g1/file_stream",), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-03-02 11:55:43,559 WARNING FileStreamThread:3921 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic_UNet_%5B'CTV1'%5D/17z6q4g1/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x120544610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x1200107c0>>, args: ("https://api.wandb.ai/files/wwy/Basic_UNet_['CTV1']/17z6q4g1/file_stream",), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-03-02 11:56:00,052 WARNING FileStreamThread:3921 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic_UNet_%5B'CTV1'%5D/17z6q4g1/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x120544f40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x1200107c0>>, args: ("https://api.wandb.ai/files/wwy/Basic_UNet_['CTV1']/17z6q4g1/file_stream",), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-03-02 11:56:32,632 WARNING FileStreamThread:3921 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic_UNet_%5B'CTV1'%5D/17z6q4g1/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x120544ee0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x1200107c0>>, args: ("https://api.wandb.ai/files/wwy/Basic_UNet_['CTV1']/17z6q4g1/file_stream",), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-03-02 11:57:52,069 WARNING FileStreamThread:3921 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic_UNet_%5B'CTV1'%5D/17z6q4g1/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1205430a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x1200107c0>>, args: ("https://api.wandb.ai/files/wwy/Basic_UNet_['CTV1']/17z6q4g1/file_stream",), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-03-02 12:00:30,056 WARNING FileStreamThread:3921 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic_UNet_%5B'CTV1'%5D/17z6q4g1/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12006f820>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x1200107c0>>, args: ("https://api.wandb.ai/files/wwy/Basic_UNet_['CTV1']/17z6q4g1/file_stream",), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-03-02 12:02:57,429 INFO    SenderThread:3921 [sender.py:finish():1075] shutting down sender
2022-03-02 12:02:57,429 INFO    SenderThread:3921 [dir_watcher.py:finish():283] shutting down directory watcher
2022-03-02 12:02:57,758 INFO    SenderThread:3921 [dir_watcher.py:finish():313] scan: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files
2022-03-02 12:02:57,759 INFO    SenderThread:3921 [dir_watcher.py:finish():327] scan save: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/requirements.txt requirements.txt
2022-03-02 12:02:57,759 INFO    SenderThread:3921 [dir_watcher.py:finish():327] scan save: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/output.log output.log
2022-03-02 12:02:57,767 INFO    SenderThread:3921 [dir_watcher.py:finish():327] scan save: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/config.yaml config.yaml
2022-03-02 12:02:57,770 INFO    SenderThread:3921 [dir_watcher.py:finish():327] scan save: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/wandb-summary.json wandb-summary.json
2022-03-02 12:02:57,776 INFO    SenderThread:3921 [dir_watcher.py:finish():327] scan save: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/conda-environment.yaml conda-environment.yaml
2022-03-02 12:02:57,779 INFO    SenderThread:3921 [dir_watcher.py:finish():327] scan save: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/wandb-metadata.json wandb-metadata.json
2022-03-02 12:02:57,780 INFO    SenderThread:3921 [file_pusher.py:finish():177] shutting down file pusher
2022-03-02 12:02:57,780 INFO    SenderThread:3921 [file_pusher.py:join():182] waiting for file pusher
2022-03-02 12:02:59,215 INFO    Thread-13 :3921 [upload_job.py:push():137] Uploaded file /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/output.log
2022-03-02 12:02:59,225 INFO    Thread-15 :3921 [upload_job.py:push():137] Uploaded file /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/wandb-summary.json
2022-03-02 12:02:59,252 INFO    Thread-14 :3921 [upload_job.py:push():137] Uploaded file /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/config.yaml
2022-03-02 12:02:59,269 INFO    Thread-16 :3921 [upload_job.py:push():137] Uploaded file /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/conda-environment.yaml
2022-03-02 12:02:59,269 INFO    Thread-12 :3921 [upload_job.py:push():137] Uploaded file /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220302_114759-17z6q4g1/files/requirements.txt
2022-03-02 12:05:05,679 INFO    MainThread:3921 [internal.py:handle_exit():79] Internal process exited
