2022-02-25 14:25:36,995 INFO    MainThread:6177 [internal.py:wandb_internal():89] W&B internal server running at pid: 6177, started at: 2022-02-25 14:25:36.995838
2022-02-25 14:25:36,996 DEBUG   HandlerThread:6177 [handler.py:handle_request():131] handle_request: check_version
2022-02-25 14:25:36,996 INFO    WriterThread:6177 [datastore.py:open_for_write():77] open: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/run-1iy1xbld.wandb
2022-02-25 14:25:36,997 DEBUG   SenderThread:6177 [sender.py:send():235] send: header
2022-02-25 14:25:36,997 DEBUG   SenderThread:6177 [sender.py:send_request():249] send_request: check_version
2022-02-25 14:25:37,216 DEBUG   SenderThread:6177 [sender.py:send():235] send: run
2022-02-25 14:25:37,554 INFO    SenderThread:6177 [dir_watcher.py:__init__():169] watching files in: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files
2022-02-25 14:25:37,555 INFO    SenderThread:6177 [sender.py:_start_run_threads():809] run started: 1iy1xbld with start time 1645795536
2022-02-25 14:25:37,555 DEBUG   SenderThread:6177 [sender.py:send():235] send: summary
2022-02-25 14:25:37,556 INFO    SenderThread:6177 [sender.py:_save_file():944] saving file wandb-summary.json with policy end
2022-02-25 14:25:37,558 DEBUG   HandlerThread:6177 [handler.py:handle_request():131] handle_request: run_start
2022-02-25 14:25:37,560 DEBUG   HandlerThread:6177 [meta.py:__init__():36] meta init
2022-02-25 14:25:37,561 DEBUG   HandlerThread:6177 [meta.py:__init__():50] meta init done
2022-02-25 14:25:37,566 DEBUG   HandlerThread:6177 [meta.py:probe():210] probe
2022-02-25 14:25:37,570 DEBUG   HandlerThread:6177 [git.py:repo():33] git repository is invalid
2022-02-25 14:25:37,570 DEBUG   HandlerThread:6177 [meta.py:_save_pip():54] save pip
2022-02-25 14:25:37,571 DEBUG   HandlerThread:6177 [meta.py:_save_pip():68] save pip done
2022-02-25 14:25:37,571 DEBUG   HandlerThread:6177 [meta.py:_save_conda():75] save conda
2022-02-25 14:25:38,559 INFO    Thread-8  :6177 [dir_watcher.py:_on_file_created():217] file/dir created: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/wandb-summary.json
2022-02-25 14:25:38,559 INFO    Thread-8  :6177 [dir_watcher.py:_on_file_created():217] file/dir created: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/conda-environment.yaml
2022-02-25 14:25:38,559 INFO    Thread-8  :6177 [dir_watcher.py:_on_file_created():217] file/dir created: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/requirements.txt
2022-02-25 14:25:41,107 DEBUG   HandlerThread:6177 [meta.py:_save_conda():85] save conda done
2022-02-25 14:25:41,107 DEBUG   HandlerThread:6177 [meta.py:probe():248] probe done
2022-02-25 14:25:41,109 DEBUG   SenderThread:6177 [sender.py:send():235] send: files
2022-02-25 14:25:41,109 INFO    SenderThread:6177 [sender.py:_save_file():944] saving file wandb-metadata.json with policy now
2022-02-25 14:25:41,113 DEBUG   HandlerThread:6177 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 14:25:41,113 DEBUG   SenderThread:6177 [sender.py:send_request():249] send_request: stop_status
2022-02-25 14:25:41,495 DEBUG   SenderThread:6177 [sender.py:send():235] send: config
2022-02-25 14:25:41,573 INFO    Thread-8  :6177 [dir_watcher.py:_on_file_modified():230] file/dir modified: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/conda-environment.yaml
2022-02-25 14:25:41,574 INFO    Thread-8  :6177 [dir_watcher.py:_on_file_created():217] file/dir created: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/output.log
2022-02-25 14:25:41,574 INFO    Thread-8  :6177 [dir_watcher.py:_on_file_created():217] file/dir created: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/wandb-metadata.json
2022-02-25 14:25:42,323 INFO    Thread-11 :6177 [upload_job.py:push():137] Uploaded file /var/folders/wb/gdwc4q3s1x3cv4bftb9vssb00000gn/T/tmpef6i3v_vwandb/2t608jbb-wandb-metadata.json
2022-02-25 14:25:43,584 INFO    Thread-8  :6177 [dir_watcher.py:_on_file_modified():230] file/dir modified: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/output.log
2022-02-25 14:25:56,510 DEBUG   HandlerThread:6177 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 14:25:56,510 DEBUG   SenderThread:6177 [sender.py:send_request():249] send_request: stop_status
2022-02-25 14:26:06,936 DEBUG   SenderThread:6177 [sender.py:send():235] send: stats
2022-02-25 14:26:07,701 INFO    Thread-8  :6177 [dir_watcher.py:_on_file_modified():230] file/dir modified: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/output.log
2022-02-25 14:26:08,706 INFO    Thread-8  :6177 [dir_watcher.py:_on_file_modified():230] file/dir modified: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/config.yaml
2022-02-25 14:26:09,712 INFO    Thread-8  :6177 [dir_watcher.py:_on_file_modified():230] file/dir modified: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/output.log
2022-02-25 14:26:12,364 DEBUG   HandlerThread:6177 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 14:26:12,365 DEBUG   SenderThread:6177 [sender.py:send_request():249] send_request: stop_status
2022-02-25 14:26:27,766 DEBUG   HandlerThread:6177 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 14:26:27,768 DEBUG   SenderThread:6177 [sender.py:send_request():249] send_request: stop_status
2022-02-25 14:26:38,540 DEBUG   SenderThread:6177 [sender.py:send():235] send: stats
2022-02-25 14:26:43,186 DEBUG   HandlerThread:6177 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 14:26:43,190 DEBUG   SenderThread:6177 [sender.py:send_request():249] send_request: stop_status
2022-02-25 14:26:58,703 DEBUG   HandlerThread:6177 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 14:26:58,715 DEBUG   SenderThread:6177 [sender.py:send_request():249] send_request: stop_status
2022-02-25 14:27:09,864 DEBUG   SenderThread:6177 [sender.py:send():235] send: stats
2022-02-25 14:27:15,076 DEBUG   HandlerThread:6177 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 14:27:15,077 DEBUG   SenderThread:6177 [sender.py:send_request():249] send_request: stop_status
2022-02-25 14:27:31,377 DEBUG   HandlerThread:6177 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 14:27:31,388 DEBUG   SenderThread:6177 [sender.py:send_request():249] send_request: stop_status
2022-02-25 14:27:41,333 DEBUG   SenderThread:6177 [sender.py:send():235] send: stats
2022-02-25 14:27:46,938 DEBUG   HandlerThread:6177 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 14:27:47,028 DEBUG   SenderThread:6177 [sender.py:send_request():249] send_request: stop_status
2022-02-25 14:28:00,844 ERROR   SenderThread:6177 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x11b15c220>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11b15c220>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11b15c220>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2022-02-25 14:28:06,162 WARNING MainThread:6177 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-25 14:28:11,187 WARNING MainThread:6177 [internal.py:is_dead():380] Internal process exiting, parent pid 6112 disappeared
2022-02-25 14:28:11,204 ERROR   MainThread:6177 [internal.py:wandb_internal():148] Internal process shutdown.
2022-02-25 14:28:11,475 INFO    WriterThread:6177 [datastore.py:close():281] close: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/run-1iy1xbld.wandb
2022-02-25 14:28:12,031 INFO    HandlerThread:6177 [handler.py:finish():739] shutting down handler
2022-02-25 14:30:18,306 WARNING FileStreamThread:6177 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: ('Connection aborted.', OSError(65, 'No route to host')). func: <bound method Session.post of <requests.sessions.Session object at 0x11b0cb760>>, args: ('https://api.wandb.ai/files/wwy/Basic UNet/1iy1xbld/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-02-25 14:30:20,526 WARNING FileStreamThread:6177 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic%20UNet/1iy1xbld/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11b301760>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x11b0cb760>>, args: ('https://api.wandb.ai/files/wwy/Basic UNet/1iy1xbld/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-02-25 14:30:25,207 WARNING FileStreamThread:6177 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic%20UNet/1iy1xbld/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11b301820>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x11b0cb760>>, args: ('https://api.wandb.ai/files/wwy/Basic UNet/1iy1xbld/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-02-25 14:30:33,239 WARNING FileStreamThread:6177 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic%20UNet/1iy1xbld/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11b3019d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x11b0cb760>>, args: ('https://api.wandb.ai/files/wwy/Basic UNet/1iy1xbld/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-02-25 14:30:50,261 WARNING FileStreamThread:6177 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic%20UNet/1iy1xbld/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11b301a60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x11b0cb760>>, args: ('https://api.wandb.ai/files/wwy/Basic UNet/1iy1xbld/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-02-25 14:31:25,332 WARNING FileStreamThread:6177 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic%20UNet/1iy1xbld/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11b301880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x11b0cb760>>, args: ('https://api.wandb.ai/files/wwy/Basic UNet/1iy1xbld/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-02-25 14:32:30,075 WARNING FileStreamThread:6177 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic%20UNet/1iy1xbld/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11b300160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x11b0cb760>>, args: ('https://api.wandb.ai/files/wwy/Basic UNet/1iy1xbld/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-02-25 14:34:56,158 WARNING FileStreamThread:6177 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic%20UNet/1iy1xbld/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11b159640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x11b0cb760>>, args: ('https://api.wandb.ai/files/wwy/Basic UNet/1iy1xbld/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-02-25 14:39:51,242 WARNING FileStreamThread:6177 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic%20UNet/1iy1xbld/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11b159580>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x11b0cb760>>, args: ('https://api.wandb.ai/files/wwy/Basic UNet/1iy1xbld/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-02-25 14:45:08,139 WARNING FileStreamThread:6177 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/wwy/Basic%20UNet/1iy1xbld/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11b1590a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x11b0cb760>>, args: ('https://api.wandb.ai/files/wwy/Basic UNet/1iy1xbld/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-02-25 14:48:12,559 INFO    SenderThread:6177 [sender.py:finish():1075] shutting down sender
2022-02-25 14:48:12,565 INFO    SenderThread:6177 [dir_watcher.py:finish():283] shutting down directory watcher
2022-02-25 14:48:12,735 INFO    SenderThread:6177 [dir_watcher.py:finish():313] scan: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files
2022-02-25 14:48:12,739 INFO    SenderThread:6177 [dir_watcher.py:finish():327] scan save: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/requirements.txt requirements.txt
2022-02-25 14:48:12,744 INFO    SenderThread:6177 [dir_watcher.py:finish():327] scan save: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/output.log output.log
2022-02-25 14:48:12,744 INFO    SenderThread:6177 [dir_watcher.py:finish():327] scan save: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/config.yaml config.yaml
2022-02-25 14:48:12,744 INFO    SenderThread:6177 [dir_watcher.py:finish():327] scan save: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/wandb-summary.json wandb-summary.json
2022-02-25 14:48:12,756 INFO    SenderThread:6177 [dir_watcher.py:finish():327] scan save: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/conda-environment.yaml conda-environment.yaml
2022-02-25 14:48:12,756 INFO    SenderThread:6177 [dir_watcher.py:finish():327] scan save: /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/wandb-metadata.json wandb-metadata.json
2022-02-25 14:48:12,756 INFO    SenderThread:6177 [file_pusher.py:finish():177] shutting down file pusher
2022-02-25 14:48:12,756 INFO    SenderThread:6177 [file_pusher.py:join():182] waiting for file pusher
2022-02-25 14:48:14,231 INFO    Thread-13 :6177 [upload_job.py:push():137] Uploaded file /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/output.log
2022-02-25 14:48:14,232 INFO    Thread-16 :6177 [upload_job.py:push():137] Uploaded file /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/conda-environment.yaml
2022-02-25 14:48:14,235 INFO    Thread-14 :6177 [upload_job.py:push():137] Uploaded file /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/config.yaml
2022-02-25 14:48:14,237 INFO    Thread-15 :6177 [upload_job.py:push():137] Uploaded file /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/wandb-summary.json
2022-02-25 14:48:14,264 INFO    Thread-12 :6177 [upload_job.py:push():137] Uploaded file /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220225_142536-1iy1xbld/files/requirements.txt
2022-02-25 14:50:12,606 INFO    MainThread:6177 [internal.py:handle_exit():79] Internal process exited
